    Detection:
      type: object
      properties:
        'activationType':
          type: string
        'additionalDataFlag':
          type: string
        'additionalEltNumbers':
          type: integer
        'aircraft24BitAddressHex':
          type: string
        'aircraft24BitAddressOctal':
          type: string
        'aircraftCallsign':
          type: string
        'aircraftOperator':
          type: string
        'aircraftRegistrationMarking':
          type: string
        'aircraftSerialNumber':
          type: integer
        'auxiliaryRadioLocatingDevice':
          type: string
        'bch2':
          type: string
        'beaconSerialNumber':
          type: integer
        'beaconType':
          type: string
        'cSCertNumberPresent':
          type: boolean
        'cSTypeApproval':
          type: integer
        'cSTypeApprovalNumber':
          type: integer
        'coarsePositionLatitude':
          type: number
        'coarsePositionLongitude':
          type: number
        'countryCode':
          type: integer
        'countryOfRegistration':
          type: string
        'disabled':
          type: boolean
        'eltIdentityType':
          type: string
        'emergencyCodeFlag':
          type: string
        'emergencyCodePresent':
          type: boolean
        'encodedPositionSource':
          type: string
        'error':
          type: string
        'errorCorrectingCode1':
          type: string
        'errorCorrectingCode2':
          type: string
        'fireFlag':
          type: boolean
        'fixedBits':
          type: string
        'hexData':
          type: string
        'hexId':
          type: string
        'homing121_5MHz':
          type: boolean
        'idPosition':
          type: string
        'isLongMessageDefault':
          type: boolean
        'latitude':
          type: number
        'longitude':
          type: number
        'medicalHelpFlag':
          type: boolean
        'messageType':
          type: string
        'nationalUse':
          type: string
        'natureOfDistress':
          type: string
        'offsetPositionLatitudeDiff':
          type: number
        'offsetPositionLongitudeDiff':
          type: number
        'orbitography4Bits':
          type: string
        'orbitographyData':
          type: string
        'orbitographyId':
          type: string
        'pdf2':
          type: string
        'protocolType':
          type: string
        'radioCallsign':
          type: string
        'rlmCapabilityType':
          type: string
        'rlmCapabilityType1Auto':
          type: boolean
        'rlmCapabilityType2Manual':
          type: boolean
        'rlmReceivedType1Auto':
          type: boolean
        'rlmReceivedType2Manual':
          type: boolean
        'rlsId':
          type: integer
        'rlsMmsiLast6Digits':
          type: string
        'rlsProviderId':
          type: string
        'rlsTacNumber':
          type: string
        'serialNumber':
          type: integer
        'shipMmsi':
          type: integer
        'shipMmsiLast6Digits':
          type: string
        'shipSecurityMmsi':
          type: integer
        'spare':
          type: string
        'specificBeaconNumber':
          type: string
        'specificEltNumber':
          type: integer
        'supplementaryData':
          type: string
        'uSManufacturerId':
          type: integer
        'uSModelId':
          type: integer
        'uSNationalUse':
          type: string
        'uSRunNumber':
          type: integer
        'uSSequenceNumber':
          type: integer
        'userProtocolType':
          type: string
